application:
  bannerMessage: ""
  environment: DEV
  nlp: "true"

logging:
  level:
    com:
      k2:
        nemesis: TRACE

server:
  servlet:
    session:
      cookie:
        http-only: "true"

spring:
  servlet:
    multipart:
      enabled: "true"
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: "false"
  datasource:
    jdbc-url: jdbc:hsqldb:file:./home/db/nlp-db;DB_CLOSE_DELAY=-1
    username: sa
    encpassword: Mi4CRQEU9EqUzEjb3MYhCA==:PZt8lB6lxGcGE2FQrCYO1g==
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.HSQLDialect
    properties:
      hibernate:
        format_sql: true
    show-sql: false

nlp:
  categoryRootLocation: ./home/templates
  templates:
    - simple.docx
